name: Tests

on: [push, workflow_dispatch]

permissions: {}
jobs:
  runPush:
    permissions:
      contents: write # for Update bundles

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Apply Patch
      run: |
        cd ./base
        git tag -f base
        git am ../patches/*

    - name: Run unit tests
      run: cd ./base && ./gradlew clean cleanTest test --stacktrace
